name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:
  
    runs-on: self-hosted
    #run the code in the agent
    steps:
    - uses: actions/checkout@v2
      with:
          clean: true
          

    - name: Configure CMake
      
      run: cmake -E make_directory ${{github.workspace}}/cpp_project/build

    - name: Build

      run: |
        cd ${{github.workspace}}/cpp_project/build
        CC=clang CXX=clang++ cmake ..
        cmake --build .

    - name: c++ Test

      run: |
        cd ${{github.workspace}}/cpp_project/build
        ctest 

    - name: Python Test

      run: |
        cd ${{github.workspace}}/py
        python3 -m pytest

    - name: Static analysis cppcheck & Pylint

      run: |
        cd ${{github.workspace}}/cpp_project
        cppcheck --enable=all .
        cd ${{github.workspace}}/py
        pylint --exit-zero ./tests
        pylint --exit-zero ./acme_mylib

    - name: Dynamic check

      run: |
        cd ${{github.workspace}}/cpp_project/build/app
        valgrind --tool=memcheck --leak-check=yes --track-origins=yes ./app
        
